# Generated by Django 2.2.3 on 2019-08-22 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='tag',
            new_name='tags',
        ),
    ]
